services:

  api:
    build: .
    container_name: api-rate-limiter

    ports:
      - "3000:3000"

    environment:
      PORT: 3000
      REDIS_URL: redis://redis:6379
      GENERAL_RATE_LIMIT: ${GENERAL_RATE_LIMIT}
      GENERAL_RATE_WINDOW: ${GENERAL_RATE_WINDOW}
      STRICT_RATE_LIMIT: ${STRICT_RATE_LIMIT}
      STRICT_RATE_WINDOW: ${STRICT_RATE_WINDOW}
      TOKEN_BUCKET_CAPACITY: ${TOKEN_BUCKET_CAPACITY}
      TOKEN_BUCKET_REFILL_RATE: ${TOKEN_BUCKET_REFILL_RATE}

    depends_on:
      redis:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/ready', r => process.exit(r.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 10s
      timeout: 5s
      retries: 5


  redis:
    image: redis:7-alpine
    container_name: api-rate-limiter-redis

    ports:
      - "6379:6379"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5